// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: com/digitalasset/canton/admin/participant/v30/party_management_service.proto

package v30

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PartyManagementService_AddPartyAsync_FullMethodName               = "/com.digitalasset.canton.admin.participant.v30.PartyManagementService/AddPartyAsync"
	PartyManagementService_AddPartyWithAcsAsync_FullMethodName        = "/com.digitalasset.canton.admin.participant.v30.PartyManagementService/AddPartyWithAcsAsync"
	PartyManagementService_GetAddPartyStatus_FullMethodName           = "/com.digitalasset.canton.admin.participant.v30.PartyManagementService/GetAddPartyStatus"
	PartyManagementService_ExportPartyAcs_FullMethodName              = "/com.digitalasset.canton.admin.participant.v30.PartyManagementService/ExportPartyAcs"
	PartyManagementService_ImportPartyAcs_FullMethodName              = "/com.digitalasset.canton.admin.participant.v30.PartyManagementService/ImportPartyAcs"
	PartyManagementService_GetHighestOffsetByTimestamp_FullMethodName = "/com.digitalasset.canton.admin.participant.v30.PartyManagementService/GetHighestOffsetByTimestamp"
	PartyManagementService_ClearPartyOnboardingFlag_FullMethodName    = "/com.digitalasset.canton.admin.participant.v30.PartyManagementService/ClearPartyOnboardingFlag"
)

// PartyManagementServiceClient is the client API for PartyManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// The PartyManagementService allows modifying party hosting on participants.
//
// Note that ACS refers to Active Contract Set.
//
// Important: The online and offline party replication endpoints serve distinct workflows,
// and must not be combined.
type PartyManagementServiceClient interface {
	// Online party replication endpoint.
	//
	// Initiate adding a party already hosted on one or more source participants to this
	// target participant in the specified synchronizer.
	// Performs some checks synchronously and then starts the party addition asynchronously.
	//
	// Depends on the party authorizing the PartyToParticipant topology proposal at the
	// specified topology_serial prior or concurrently to this endpoint. On the other hand,
	// this target participant authorizes the topology proposal as part of this endpoint in
	// a specific, intermediate step, and therefore the target participant signature must not
	// already be in place prior to the call.
	//
	//	This operation assumes full trust in the source participant to provide a complete and
	//	untampered state. Because the target participant cannot independently verify
	//	the historical provenance of the imported contracts,
	//	validation is performed on a best-effort basis.
	//	Use only when the source participant is a known, trusted authority.
	//
	// Returns a 'request_id' that is stable across each retry with the same request parameters.
	AddPartyAsync(ctx context.Context, in *AddPartyAsyncRequest, opts ...grpc.CallOption) (*AddPartyAsyncResponse, error)
	// Online party replication endpoint.
	//
	// Add a party already hosted on one or more source participants to this target participant
	// in the specified synchronizer along with the party's Active Contract Set (ACS) streamed
	// in the request.
	// Uploads the ACS synchronously and then performs the party addition asynchronously.
	//
	// This operation assumes full trust in the source participant to provide a complete and
	// untampered state. Because the target participant cannot independently verify
	// the historical provenance of the imported contracts,
	// validation is performed on a best-effort basis.
	// Use only when the source participant is a known, trusted authority.
	//
	// Returns a 'request_id' that is stable across each retry with the same request parameters.
	AddPartyWithAcsAsync(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AddPartyWithAcsAsyncRequest, AddPartyWithAcsAsyncResponse], error)
	// Online party replication endpoint.
	//
	// Status endpoint that given an add_party_request_id returns status information about progress,
	// completion, or errors of a previous call to AddPartyAsync on the source or target
	// participant, or a previous call to AddPartyWithAcs on the target participant.
	//
	// Note that the status reflects the state as perceived by this participant and does not
	// imply the state of other participants. The status on the target participant is more
	// authoritative as the target participant drives the process of adding the party. For example
	// when the target participant status indicates "completed", the party has been added
	// successfully.
	GetAddPartyStatus(ctx context.Context, in *GetAddPartyStatusRequest, opts ...grpc.CallOption) (*GetAddPartyStatusResponse, error)
	// Online and offline party replication ACS export.
	//
	// Exports the ACS of a single party from a source participant, so that the party can be
	// replicated onto a target participant.
	//
	// This endpoint works in conjunction with the AddPartyWithAcs and ImportPartyAcs endpoints.
	ExportPartyAcs(ctx context.Context, in *ExportPartyAcsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportPartyAcsResponse], error)
	// Offline party replication focused ACS import.
	//
	// Imports the party's ACS into the target participant.
	//
	// This operation assumes the provided snapshot
	// contains the complete and untampered ACS originating from a trusted source participant.
	// Because the target participant cannot independently verify the historical provenance
	// of the imported contracts, validation is performed on a best-effort basis,
	// even if `contractImportMode` is `Validation`.
	// Use only when the provided snapshot comes from a known, trusted authority.
	//
	// This endpoint works in conjunction with the ExportPartyAcs endpoint.
	ImportPartyAcs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportPartyAcsRequest, ImportPartyAcsResponse], error)
	// For a given timestamp, find the highest ledger offset among all events that have record time <= timestamp.
	//
	// Returns a ledger offset, or an error otherwise. Depending on the error cause, a retry may make sense.
	// Retryable errors are defined as: OUT_OF_RANGE/INVALID_TIMESTAMP_PARTY_MANAGEMENT_ERROR.
	//
	// The returned offset is guaranteed to be "clean", meaning all events have been processed fully and
	// published to the Ledger API DB until the requested timestamp. Furthermore, the endpoint synchronizes
	// with the participant's local cache, ensuring the returned offset is immediately queryable via
	// subsequent Ledger API calls.
	GetHighestOffsetByTimestamp(ctx context.Context, in *GetHighestOffsetByTimestampRequest, opts ...grpc.CallOption) (*GetHighestOffsetByTimestampResponse, error)
	// Offline party replication endpoint.
	//
	// Instructs the participant to unilaterally clear the 'onboarding' flag for a
	// given party on its party-to-participant topology mapping.
	//
	// The RPC first attempts to clear the flag immediately. If this is not yet safe
	// (e.g., due to potential in-flight transactions), it schedules an idempotent
	// background task to propose the clearance at the appropriate, safe time.
	//
	// This RPC is idempotent and designed to be polled.
	//
	// Response status:
	//   - onboarded = true: The flag is successfully cleared or was already clear.
	//   - onboarded = false: The flag is not yet cleared. A background task is scheduled
	//     (or was already pending).
	//
	// Prerequisites:
	// - An 'onboarding=true' mapping must exist for the party on this participant.
	// - The participant must be connected to the requested synchronizer.
	ClearPartyOnboardingFlag(ctx context.Context, in *ClearPartyOnboardingFlagRequest, opts ...grpc.CallOption) (*ClearPartyOnboardingFlagResponse, error)
}

type partyManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartyManagementServiceClient(cc grpc.ClientConnInterface) PartyManagementServiceClient {
	return &partyManagementServiceClient{cc}
}

func (c *partyManagementServiceClient) AddPartyAsync(ctx context.Context, in *AddPartyAsyncRequest, opts ...grpc.CallOption) (*AddPartyAsyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPartyAsyncResponse)
	err := c.cc.Invoke(ctx, PartyManagementService_AddPartyAsync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyManagementServiceClient) AddPartyWithAcsAsync(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AddPartyWithAcsAsyncRequest, AddPartyWithAcsAsyncResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PartyManagementService_ServiceDesc.Streams[0], PartyManagementService_AddPartyWithAcsAsync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AddPartyWithAcsAsyncRequest, AddPartyWithAcsAsyncResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PartyManagementService_AddPartyWithAcsAsyncClient = grpc.ClientStreamingClient[AddPartyWithAcsAsyncRequest, AddPartyWithAcsAsyncResponse]

func (c *partyManagementServiceClient) GetAddPartyStatus(ctx context.Context, in *GetAddPartyStatusRequest, opts ...grpc.CallOption) (*GetAddPartyStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAddPartyStatusResponse)
	err := c.cc.Invoke(ctx, PartyManagementService_GetAddPartyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyManagementServiceClient) ExportPartyAcs(ctx context.Context, in *ExportPartyAcsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportPartyAcsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PartyManagementService_ServiceDesc.Streams[1], PartyManagementService_ExportPartyAcs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportPartyAcsRequest, ExportPartyAcsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PartyManagementService_ExportPartyAcsClient = grpc.ServerStreamingClient[ExportPartyAcsResponse]

func (c *partyManagementServiceClient) ImportPartyAcs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportPartyAcsRequest, ImportPartyAcsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PartyManagementService_ServiceDesc.Streams[2], PartyManagementService_ImportPartyAcs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImportPartyAcsRequest, ImportPartyAcsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PartyManagementService_ImportPartyAcsClient = grpc.ClientStreamingClient[ImportPartyAcsRequest, ImportPartyAcsResponse]

func (c *partyManagementServiceClient) GetHighestOffsetByTimestamp(ctx context.Context, in *GetHighestOffsetByTimestampRequest, opts ...grpc.CallOption) (*GetHighestOffsetByTimestampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHighestOffsetByTimestampResponse)
	err := c.cc.Invoke(ctx, PartyManagementService_GetHighestOffsetByTimestamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyManagementServiceClient) ClearPartyOnboardingFlag(ctx context.Context, in *ClearPartyOnboardingFlagRequest, opts ...grpc.CallOption) (*ClearPartyOnboardingFlagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearPartyOnboardingFlagResponse)
	err := c.cc.Invoke(ctx, PartyManagementService_ClearPartyOnboardingFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartyManagementServiceServer is the server API for PartyManagementService service.
// All implementations must embed UnimplementedPartyManagementServiceServer
// for forward compatibility.
//
// *
// The PartyManagementService allows modifying party hosting on participants.
//
// Note that ACS refers to Active Contract Set.
//
// Important: The online and offline party replication endpoints serve distinct workflows,
// and must not be combined.
type PartyManagementServiceServer interface {
	// Online party replication endpoint.
	//
	// Initiate adding a party already hosted on one or more source participants to this
	// target participant in the specified synchronizer.
	// Performs some checks synchronously and then starts the party addition asynchronously.
	//
	// Depends on the party authorizing the PartyToParticipant topology proposal at the
	// specified topology_serial prior or concurrently to this endpoint. On the other hand,
	// this target participant authorizes the topology proposal as part of this endpoint in
	// a specific, intermediate step, and therefore the target participant signature must not
	// already be in place prior to the call.
	//
	//	This operation assumes full trust in the source participant to provide a complete and
	//	untampered state. Because the target participant cannot independently verify
	//	the historical provenance of the imported contracts,
	//	validation is performed on a best-effort basis.
	//	Use only when the source participant is a known, trusted authority.
	//
	// Returns a 'request_id' that is stable across each retry with the same request parameters.
	AddPartyAsync(context.Context, *AddPartyAsyncRequest) (*AddPartyAsyncResponse, error)
	// Online party replication endpoint.
	//
	// Add a party already hosted on one or more source participants to this target participant
	// in the specified synchronizer along with the party's Active Contract Set (ACS) streamed
	// in the request.
	// Uploads the ACS synchronously and then performs the party addition asynchronously.
	//
	// This operation assumes full trust in the source participant to provide a complete and
	// untampered state. Because the target participant cannot independently verify
	// the historical provenance of the imported contracts,
	// validation is performed on a best-effort basis.
	// Use only when the source participant is a known, trusted authority.
	//
	// Returns a 'request_id' that is stable across each retry with the same request parameters.
	AddPartyWithAcsAsync(grpc.ClientStreamingServer[AddPartyWithAcsAsyncRequest, AddPartyWithAcsAsyncResponse]) error
	// Online party replication endpoint.
	//
	// Status endpoint that given an add_party_request_id returns status information about progress,
	// completion, or errors of a previous call to AddPartyAsync on the source or target
	// participant, or a previous call to AddPartyWithAcs on the target participant.
	//
	// Note that the status reflects the state as perceived by this participant and does not
	// imply the state of other participants. The status on the target participant is more
	// authoritative as the target participant drives the process of adding the party. For example
	// when the target participant status indicates "completed", the party has been added
	// successfully.
	GetAddPartyStatus(context.Context, *GetAddPartyStatusRequest) (*GetAddPartyStatusResponse, error)
	// Online and offline party replication ACS export.
	//
	// Exports the ACS of a single party from a source participant, so that the party can be
	// replicated onto a target participant.
	//
	// This endpoint works in conjunction with the AddPartyWithAcs and ImportPartyAcs endpoints.
	ExportPartyAcs(*ExportPartyAcsRequest, grpc.ServerStreamingServer[ExportPartyAcsResponse]) error
	// Offline party replication focused ACS import.
	//
	// Imports the party's ACS into the target participant.
	//
	// This operation assumes the provided snapshot
	// contains the complete and untampered ACS originating from a trusted source participant.
	// Because the target participant cannot independently verify the historical provenance
	// of the imported contracts, validation is performed on a best-effort basis,
	// even if `contractImportMode` is `Validation`.
	// Use only when the provided snapshot comes from a known, trusted authority.
	//
	// This endpoint works in conjunction with the ExportPartyAcs endpoint.
	ImportPartyAcs(grpc.ClientStreamingServer[ImportPartyAcsRequest, ImportPartyAcsResponse]) error
	// For a given timestamp, find the highest ledger offset among all events that have record time <= timestamp.
	//
	// Returns a ledger offset, or an error otherwise. Depending on the error cause, a retry may make sense.
	// Retryable errors are defined as: OUT_OF_RANGE/INVALID_TIMESTAMP_PARTY_MANAGEMENT_ERROR.
	//
	// The returned offset is guaranteed to be "clean", meaning all events have been processed fully and
	// published to the Ledger API DB until the requested timestamp. Furthermore, the endpoint synchronizes
	// with the participant's local cache, ensuring the returned offset is immediately queryable via
	// subsequent Ledger API calls.
	GetHighestOffsetByTimestamp(context.Context, *GetHighestOffsetByTimestampRequest) (*GetHighestOffsetByTimestampResponse, error)
	// Offline party replication endpoint.
	//
	// Instructs the participant to unilaterally clear the 'onboarding' flag for a
	// given party on its party-to-participant topology mapping.
	//
	// The RPC first attempts to clear the flag immediately. If this is not yet safe
	// (e.g., due to potential in-flight transactions), it schedules an idempotent
	// background task to propose the clearance at the appropriate, safe time.
	//
	// This RPC is idempotent and designed to be polled.
	//
	// Response status:
	//   - onboarded = true: The flag is successfully cleared or was already clear.
	//   - onboarded = false: The flag is not yet cleared. A background task is scheduled
	//     (or was already pending).
	//
	// Prerequisites:
	// - An 'onboarding=true' mapping must exist for the party on this participant.
	// - The participant must be connected to the requested synchronizer.
	ClearPartyOnboardingFlag(context.Context, *ClearPartyOnboardingFlagRequest) (*ClearPartyOnboardingFlagResponse, error)
	mustEmbedUnimplementedPartyManagementServiceServer()
}

// UnimplementedPartyManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartyManagementServiceServer struct{}

func (UnimplementedPartyManagementServiceServer) AddPartyAsync(context.Context, *AddPartyAsyncRequest) (*AddPartyAsyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPartyAsync not implemented")
}
func (UnimplementedPartyManagementServiceServer) AddPartyWithAcsAsync(grpc.ClientStreamingServer[AddPartyWithAcsAsyncRequest, AddPartyWithAcsAsyncResponse]) error {
	return status.Errorf(codes.Unimplemented, "method AddPartyWithAcsAsync not implemented")
}
func (UnimplementedPartyManagementServiceServer) GetAddPartyStatus(context.Context, *GetAddPartyStatusRequest) (*GetAddPartyStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddPartyStatus not implemented")
}
func (UnimplementedPartyManagementServiceServer) ExportPartyAcs(*ExportPartyAcsRequest, grpc.ServerStreamingServer[ExportPartyAcsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ExportPartyAcs not implemented")
}
func (UnimplementedPartyManagementServiceServer) ImportPartyAcs(grpc.ClientStreamingServer[ImportPartyAcsRequest, ImportPartyAcsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ImportPartyAcs not implemented")
}
func (UnimplementedPartyManagementServiceServer) GetHighestOffsetByTimestamp(context.Context, *GetHighestOffsetByTimestampRequest) (*GetHighestOffsetByTimestampResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHighestOffsetByTimestamp not implemented")
}
func (UnimplementedPartyManagementServiceServer) ClearPartyOnboardingFlag(context.Context, *ClearPartyOnboardingFlagRequest) (*ClearPartyOnboardingFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearPartyOnboardingFlag not implemented")
}
func (UnimplementedPartyManagementServiceServer) mustEmbedUnimplementedPartyManagementServiceServer() {
}
func (UnimplementedPartyManagementServiceServer) testEmbeddedByValue() {}

// UnsafePartyManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartyManagementServiceServer will
// result in compilation errors.
type UnsafePartyManagementServiceServer interface {
	mustEmbedUnimplementedPartyManagementServiceServer()
}

func RegisterPartyManagementServiceServer(s grpc.ServiceRegistrar, srv PartyManagementServiceServer) {
	// If the following call pancis, it indicates UnimplementedPartyManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartyManagementService_ServiceDesc, srv)
}

func _PartyManagementService_AddPartyAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPartyAsyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyManagementServiceServer).AddPartyAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyManagementService_AddPartyAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyManagementServiceServer).AddPartyAsync(ctx, req.(*AddPartyAsyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyManagementService_AddPartyWithAcsAsync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PartyManagementServiceServer).AddPartyWithAcsAsync(&grpc.GenericServerStream[AddPartyWithAcsAsyncRequest, AddPartyWithAcsAsyncResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PartyManagementService_AddPartyWithAcsAsyncServer = grpc.ClientStreamingServer[AddPartyWithAcsAsyncRequest, AddPartyWithAcsAsyncResponse]

func _PartyManagementService_GetAddPartyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddPartyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyManagementServiceServer).GetAddPartyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyManagementService_GetAddPartyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyManagementServiceServer).GetAddPartyStatus(ctx, req.(*GetAddPartyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyManagementService_ExportPartyAcs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportPartyAcsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PartyManagementServiceServer).ExportPartyAcs(m, &grpc.GenericServerStream[ExportPartyAcsRequest, ExportPartyAcsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PartyManagementService_ExportPartyAcsServer = grpc.ServerStreamingServer[ExportPartyAcsResponse]

func _PartyManagementService_ImportPartyAcs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PartyManagementServiceServer).ImportPartyAcs(&grpc.GenericServerStream[ImportPartyAcsRequest, ImportPartyAcsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PartyManagementService_ImportPartyAcsServer = grpc.ClientStreamingServer[ImportPartyAcsRequest, ImportPartyAcsResponse]

func _PartyManagementService_GetHighestOffsetByTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHighestOffsetByTimestampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyManagementServiceServer).GetHighestOffsetByTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyManagementService_GetHighestOffsetByTimestamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyManagementServiceServer).GetHighestOffsetByTimestamp(ctx, req.(*GetHighestOffsetByTimestampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyManagementService_ClearPartyOnboardingFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearPartyOnboardingFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyManagementServiceServer).ClearPartyOnboardingFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartyManagementService_ClearPartyOnboardingFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyManagementServiceServer).ClearPartyOnboardingFlag(ctx, req.(*ClearPartyOnboardingFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartyManagementService_ServiceDesc is the grpc.ServiceDesc for PartyManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartyManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.digitalasset.canton.admin.participant.v30.PartyManagementService",
	HandlerType: (*PartyManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPartyAsync",
			Handler:    _PartyManagementService_AddPartyAsync_Handler,
		},
		{
			MethodName: "GetAddPartyStatus",
			Handler:    _PartyManagementService_GetAddPartyStatus_Handler,
		},
		{
			MethodName: "GetHighestOffsetByTimestamp",
			Handler:    _PartyManagementService_GetHighestOffsetByTimestamp_Handler,
		},
		{
			MethodName: "ClearPartyOnboardingFlag",
			Handler:    _PartyManagementService_ClearPartyOnboardingFlag_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddPartyWithAcsAsync",
			Handler:       _PartyManagementService_AddPartyWithAcsAsync_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ExportPartyAcs",
			Handler:       _PartyManagementService_ExportPartyAcs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ImportPartyAcs",
			Handler:       _PartyManagementService_ImportPartyAcs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "com/digitalasset/canton/admin/participant/v30/party_management_service.proto",
}
