// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: com/digitalasset/canton/admin/participant/v30/party_management_service.proto

package v30

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum indicating the permission level of the party on the target participant.
// Refer to topology.proto:`ParticipantPermission` for definitions.
type ParticipantPermission int32

const (
	ParticipantPermission_PARTICIPANT_PERMISSION_UNSPECIFIED  ParticipantPermission = 0
	ParticipantPermission_PARTICIPANT_PERMISSION_SUBMISSION   ParticipantPermission = 1
	ParticipantPermission_PARTICIPANT_PERMISSION_CONFIRMATION ParticipantPermission = 2
	ParticipantPermission_PARTICIPANT_PERMISSION_OBSERVATION  ParticipantPermission = 3
)

// Enum value maps for ParticipantPermission.
var (
	ParticipantPermission_name = map[int32]string{
		0: "PARTICIPANT_PERMISSION_UNSPECIFIED",
		1: "PARTICIPANT_PERMISSION_SUBMISSION",
		2: "PARTICIPANT_PERMISSION_CONFIRMATION",
		3: "PARTICIPANT_PERMISSION_OBSERVATION",
	}
	ParticipantPermission_value = map[string]int32{
		"PARTICIPANT_PERMISSION_UNSPECIFIED":  0,
		"PARTICIPANT_PERMISSION_SUBMISSION":   1,
		"PARTICIPANT_PERMISSION_CONFIRMATION": 2,
		"PARTICIPANT_PERMISSION_OBSERVATION":  3,
	}
)

func (x ParticipantPermission) Enum() *ParticipantPermission {
	p := new(ParticipantPermission)
	*p = x
	return p
}

func (x ParticipantPermission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParticipantPermission) Descriptor() protoreflect.EnumDescriptor {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_enumTypes[0].Descriptor()
}

func (ParticipantPermission) Type() protoreflect.EnumType {
	return &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_enumTypes[0]
}

func (x ParticipantPermission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParticipantPermission.Descriptor instead.
func (ParticipantPermission) EnumDescriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{0}
}

type AddPartyAsyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Arguments common among AddPartyAsync and AddPartyWithAcs requests.
	// Required
	Arguments     *AddPartyArguments `protobuf:"bytes,1,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPartyAsyncRequest) Reset() {
	*x = AddPartyAsyncRequest{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPartyAsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPartyAsyncRequest) ProtoMessage() {}

func (x *AddPartyAsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPartyAsyncRequest.ProtoReflect.Descriptor instead.
func (*AddPartyAsyncRequest) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddPartyAsyncRequest) GetArguments() *AddPartyArguments {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type AddPartyArguments struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The party to replicate
	// Required
	PartyId string `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// The synchronizer in which to replicate the party
	// Required
	SynchronizerId string `protobuf:"bytes,2,opt,name=synchronizer_id,json=synchronizerId,proto3" json:"synchronizer_id,omitempty"`
	// A source participant already hosting the party
	// Required
	SourceParticipantUid string `protobuf:"bytes,3,opt,name=source_participant_uid,json=sourceParticipantUid,proto3" json:"source_participant_uid,omitempty"`
	// The topology serial number of the PartyToParticipant topology transaction used to
	// add the party to this target participant.
	// Required
	TopologySerial uint32 `protobuf:"varint,4,opt,name=topology_serial,json=topologySerial,proto3" json:"topology_serial,omitempty"`
	// The permission level of the party on the target participant.
	// Required
	ParticipantPermission ParticipantPermission `protobuf:"varint,5,opt,name=participant_permission,json=participantPermission,proto3,enum=com.digitalasset.canton.admin.participant.v30.ParticipantPermission" json:"participant_permission,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AddPartyArguments) Reset() {
	*x = AddPartyArguments{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPartyArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPartyArguments) ProtoMessage() {}

func (x *AddPartyArguments) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPartyArguments.ProtoReflect.Descriptor instead.
func (*AddPartyArguments) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddPartyArguments) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *AddPartyArguments) GetSynchronizerId() string {
	if x != nil {
		return x.SynchronizerId
	}
	return ""
}

func (x *AddPartyArguments) GetSourceParticipantUid() string {
	if x != nil {
		return x.SourceParticipantUid
	}
	return ""
}

func (x *AddPartyArguments) GetTopologySerial() uint32 {
	if x != nil {
		return x.TopologySerial
	}
	return 0
}

func (x *AddPartyArguments) GetParticipantPermission() ParticipantPermission {
	if x != nil {
		return x.ParticipantPermission
	}
	return ParticipantPermission_PARTICIPANT_PERMISSION_UNSPECIFIED
}

type AddPartyAsyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier used to uniquely track the add party request.
	AddPartyRequestId string `protobuf:"bytes,1,opt,name=add_party_request_id,json=addPartyRequestId,proto3" json:"add_party_request_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddPartyAsyncResponse) Reset() {
	*x = AddPartyAsyncResponse{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPartyAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPartyAsyncResponse) ProtoMessage() {}

func (x *AddPartyAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPartyAsyncResponse.ProtoReflect.Descriptor instead.
func (*AddPartyAsyncResponse) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{2}
}

func (x *AddPartyAsyncResponse) GetAddPartyRequestId() string {
	if x != nil {
		return x.AddPartyRequestId
	}
	return ""
}

type AddPartyWithAcsAsyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw binary of the ACS snapshot to be imported
	// The binary content does not align on individual active contracts! It may contain bytes that are part of
	// an active contract, or include several active contracts - depending on how much data fits into the
	// configured gRPC message size.
	// Required
	AcsSnapshot []byte `protobuf:"bytes,1,opt,name=acs_snapshot,json=acsSnapshot,proto3" json:"acs_snapshot,omitempty"`
	// The add party arguments used for request validation and initialization.
	// Required for the first message of the stream, should be empty for subsequent messages.
	Arguments     *AddPartyArguments `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPartyWithAcsAsyncRequest) Reset() {
	*x = AddPartyWithAcsAsyncRequest{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPartyWithAcsAsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPartyWithAcsAsyncRequest) ProtoMessage() {}

func (x *AddPartyWithAcsAsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPartyWithAcsAsyncRequest.ProtoReflect.Descriptor instead.
func (*AddPartyWithAcsAsyncRequest) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{3}
}

func (x *AddPartyWithAcsAsyncRequest) GetAcsSnapshot() []byte {
	if x != nil {
		return x.AcsSnapshot
	}
	return nil
}

func (x *AddPartyWithAcsAsyncRequest) GetArguments() *AddPartyArguments {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type AddPartyWithAcsAsyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier used to uniquely track the add party request.
	AddPartyRequestId string `protobuf:"bytes,1,opt,name=add_party_request_id,json=addPartyRequestId,proto3" json:"add_party_request_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddPartyWithAcsAsyncResponse) Reset() {
	*x = AddPartyWithAcsAsyncResponse{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPartyWithAcsAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPartyWithAcsAsyncResponse) ProtoMessage() {}

func (x *AddPartyWithAcsAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPartyWithAcsAsyncResponse.ProtoReflect.Descriptor instead.
func (*AddPartyWithAcsAsyncResponse) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{4}
}

func (x *AddPartyWithAcsAsyncResponse) GetAddPartyRequestId() string {
	if x != nil {
		return x.AddPartyRequestId
	}
	return ""
}

type GetAddPartyStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The add party request ID returned by AddPartyAsync
	// Required
	AddPartyRequestId string `protobuf:"bytes,1,opt,name=add_party_request_id,json=addPartyRequestId,proto3" json:"add_party_request_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAddPartyStatusRequest) Reset() {
	*x = GetAddPartyStatusRequest{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddPartyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddPartyStatusRequest) ProtoMessage() {}

func (x *GetAddPartyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddPartyStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAddPartyStatusRequest) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAddPartyStatusRequest) GetAddPartyRequestId() string {
	if x != nil {
		return x.AddPartyRequestId
	}
	return ""
}

type GetAddPartyStatusResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        *PartyReplicationStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddPartyStatusResponse) Reset() {
	*x = GetAddPartyStatusResponse{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddPartyStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddPartyStatusResponse) ProtoMessage() {}

func (x *GetAddPartyStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddPartyStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAddPartyStatusResponse) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAddPartyStatusResponse) GetStatus() *PartyReplicationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// The PartyReplicationStatus describes the various pieces of state of a party replication.
type PartyReplicationStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Static party replication parameters.
	// required
	Parameters *PartyReplicationStatus_ReplicationParameters `protobuf:"bytes,1,opt,name=parameters,proto3" json:"parameters,omitempty"`
	// Sequencer channel agreement.
	// optional, set if there is an agreement to replicate the ACS via sequencer channel.
	Agreement *PartyReplicationStatus_SequencerChannelAgreement `protobuf:"bytes,2,opt,name=agreement,proto3" json:"agreement,omitempty"`
	// Topology authorization.
	// optional, set once the party onboarding has been authorized via topology.
	Authorization *PartyReplicationStatus_PartyReplicationAuthorization `protobuf:"bytes,3,opt,name=authorization,proto3" json:"authorization,omitempty"`
	// ACS replication progress.
	// optional, set once the ACS replication has started.
	Replication *PartyReplicationStatus_AcsReplicationProgress `protobuf:"bytes,4,opt,name=replication,proto3" json:"replication,omitempty"`
	// Indexing progress.
	// optional, set once indexing of the ACS has started.
	Indexing *PartyReplicationStatus_AcsIndexingProgress `protobuf:"bytes,5,opt,name=indexing,proto3" json:"indexing,omitempty"`
	// Whether the party has been successfully replicated to the target participant,
	// i.e. whether party replication has succeeded and is done.
	// required
	HasCompleted bool `protobuf:"varint,6,opt,name=has_completed,json=hasCompleted,proto3" json:"has_completed,omitempty"`
	// Error details.
	// optional, set when there is a transient or terminal error.
	ErrorMessage  *PartyReplicationStatus_PartyReplicationError `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyReplicationStatus) Reset() {
	*x = PartyReplicationStatus{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyReplicationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyReplicationStatus) ProtoMessage() {}

func (x *PartyReplicationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyReplicationStatus.ProtoReflect.Descriptor instead.
func (*PartyReplicationStatus) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{7}
}

func (x *PartyReplicationStatus) GetParameters() *PartyReplicationStatus_ReplicationParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *PartyReplicationStatus) GetAgreement() *PartyReplicationStatus_SequencerChannelAgreement {
	if x != nil {
		return x.Agreement
	}
	return nil
}

func (x *PartyReplicationStatus) GetAuthorization() *PartyReplicationStatus_PartyReplicationAuthorization {
	if x != nil {
		return x.Authorization
	}
	return nil
}

func (x *PartyReplicationStatus) GetReplication() *PartyReplicationStatus_AcsReplicationProgress {
	if x != nil {
		return x.Replication
	}
	return nil
}

func (x *PartyReplicationStatus) GetIndexing() *PartyReplicationStatus_AcsIndexingProgress {
	if x != nil {
		return x.Indexing
	}
	return nil
}

func (x *PartyReplicationStatus) GetHasCompleted() bool {
	if x != nil {
		return x.HasCompleted
	}
	return false
}

func (x *PartyReplicationStatus) GetErrorMessage() *PartyReplicationStatus_PartyReplicationError {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

// Exports the ACS for a given party to facilitate its replication from a source to a target participant.
//
// This request uses the party's most recent activation on the target participant to determine the precise
// historical state of the ACS to export from the source participant.
//
// "Activation" on the target participant means the new hosting arrangement has been authorized by both
// the party itself and the target participant via party-to-participant topology transactions.
//
// This request will fail if the party has not yet been activated on the target participant.
type ExportPartyAcsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the party being replicated. This party must already be active on the target participant
	// for the ACS export to succeed.
	// Required
	PartyId string `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// The identifier of the synchronizer managing the contract to be exported. This scopes the ACS export to only
	// contracts assigned to this synchronizer.
	// Required
	SynchronizerId string `protobuf:"bytes,2,opt,name=synchronizer_id,json=synchronizerId,proto3" json:"synchronizer_id,omitempty"`
	// The unique identifier of the target participant where the party will be replicated.
	// Required
	TargetParticipantUid string `protobuf:"bytes,3,opt,name=target_participant_uid,json=targetParticipantUid,proto3" json:"target_participant_uid,omitempty"`
	// The exclusive ledger offset used as a starting point to find the party's most recent activation on the target
	// participant.
	// Required
	BeginOffsetExclusive int64 `protobuf:"varint,4,opt,name=begin_offset_exclusive,json=beginOffsetExclusive,proto3" json:"begin_offset_exclusive,omitempty"`
	// The maximum duration the service will wait to find the topology transaction that activates the party on
	// the target participant.
	// If not set, the service will use a default timeout.
	// Optional
	WaitForActivationTimeout *durationpb.Duration `protobuf:"bytes,5,opt,name=wait_for_activation_timeout,json=waitForActivationTimeout,proto3" json:"wait_for_activation_timeout,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ExportPartyAcsRequest) Reset() {
	*x = ExportPartyAcsRequest{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPartyAcsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPartyAcsRequest) ProtoMessage() {}

func (x *ExportPartyAcsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPartyAcsRequest.ProtoReflect.Descriptor instead.
func (*ExportPartyAcsRequest) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{8}
}

func (x *ExportPartyAcsRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *ExportPartyAcsRequest) GetSynchronizerId() string {
	if x != nil {
		return x.SynchronizerId
	}
	return ""
}

func (x *ExportPartyAcsRequest) GetTargetParticipantUid() string {
	if x != nil {
		return x.TargetParticipantUid
	}
	return ""
}

func (x *ExportPartyAcsRequest) GetBeginOffsetExclusive() int64 {
	if x != nil {
		return x.BeginOffsetExclusive
	}
	return 0
}

func (x *ExportPartyAcsRequest) GetWaitForActivationTimeout() *durationpb.Duration {
	if x != nil {
		return x.WaitForActivationTimeout
	}
	return nil
}

type ExportPartyAcsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A chunk of the ACS snapshot. This response is streamed, with each message containing a portion of the
	// complete ACS data. The raw binary data within each chunk consists of Ledger API active contract messages,
	// specifically wrapped in `v30.active_contract.ActiveContract` messages. However, a single chunk does not
	// necessarily contain exactly one complete message.
	// This field will be populated in each streamed response.
	// Required
	Chunk         []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportPartyAcsResponse) Reset() {
	*x = ExportPartyAcsResponse{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPartyAcsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPartyAcsResponse) ProtoMessage() {}

func (x *ExportPartyAcsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPartyAcsResponse.ProtoReflect.Descriptor instead.
func (*ExportPartyAcsResponse) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{9}
}

func (x *ExportPartyAcsResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type ImportPartyAcsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw binary of the ACS snapshot to be imported.
	// The binary content does not align on individual active contracts! It may contain bytes that are part of
	// an active contract, or include several active contracts - depending on how much data fits into the
	// configured gRPC message size.
	// Required
	AcsSnapshot []byte `protobuf:"bytes,1,opt,name=acs_snapshot,json=acsSnapshot,proto3" json:"acs_snapshot,omitempty"`
	// The identifier of the synchronizer managing the contracts to be imported.
	// Only contracts in the snapshot assigned to this exact synchronizer ID will be imported.
	// Any contract that is assigned to another synchronizer will be ignored.
	// Required in the first request, ignored in all subsequent request messages.
	SynchronizerId *string `protobuf:"bytes,2,opt,name=synchronizer_id,json=synchronizerId,proto3,oneof" json:"synchronizer_id,omitempty"`
	// Custom prefix for the workflow ID to easily identify all transactions generated by this import.
	// Optional. If left empty, the service will generate a prefix such as `import-<random_UUID>`.
	// Optional in the first request, ignored in all subsequent request messages.
	WorkflowIdPrefix *string `protobuf:"bytes,3,opt,name=workflow_id_prefix,json=workflowIdPrefix,proto3,oneof" json:"workflow_id_prefix,omitempty"`
	// How imported contracts should be validated upon import.
	//
	// NOTE: The representative package IDs assigned to imported contracts must ensure proper type-checking for those contracts.
	// Importing contracts with representative_package_id's that do not type-check may cause unexpected behavior,
	// including INTERNAL errors on Ledger API read queries or incorrect Daml value representations.
	// If unsure, perform the ACS import with ContractImportMode set to CONTRACT_IMPORT_MODE_VALIDATION to ensure
	// that the assigned representative package IDs correctly validate the imported contracts.
	//
	// Required in the first request, ignored in any subsequent request messages.
	ContractImportMode *ContractImportMode `protobuf:"varint,4,opt,name=contract_import_mode,json=contractImportMode,proto3,enum=com.digitalasset.canton.admin.participant.v30.ContractImportMode,oneof" json:"contract_import_mode,omitempty"`
	// The representative package ID override rules to be applied during import.
	//
	// Optional in the first request, ignored in any subsequent request messages.
	RepresentativePackageIdOverride *RepresentativePackageIdOverride `protobuf:"bytes,5,opt,name=representative_package_id_override,json=representativePackageIdOverride,proto3,oneof" json:"representative_package_id_override,omitempty"`
	// The ID of the party for which the ACS is being imported.
	// If provided, and the protocol version is 35 or higher, this enables
	// crash-resilient scheduling for clearing the onboarding flag.
	//
	// Optional in the first request, ignored in all subsequent request messages.
	PartyId       *string `protobuf:"bytes,6,opt,name=party_id,json=partyId,proto3,oneof" json:"party_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportPartyAcsRequest) Reset() {
	*x = ImportPartyAcsRequest{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportPartyAcsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportPartyAcsRequest) ProtoMessage() {}

func (x *ImportPartyAcsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportPartyAcsRequest.ProtoReflect.Descriptor instead.
func (*ImportPartyAcsRequest) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{10}
}

func (x *ImportPartyAcsRequest) GetAcsSnapshot() []byte {
	if x != nil {
		return x.AcsSnapshot
	}
	return nil
}

func (x *ImportPartyAcsRequest) GetSynchronizerId() string {
	if x != nil && x.SynchronizerId != nil {
		return *x.SynchronizerId
	}
	return ""
}

func (x *ImportPartyAcsRequest) GetWorkflowIdPrefix() string {
	if x != nil && x.WorkflowIdPrefix != nil {
		return *x.WorkflowIdPrefix
	}
	return ""
}

func (x *ImportPartyAcsRequest) GetContractImportMode() ContractImportMode {
	if x != nil && x.ContractImportMode != nil {
		return *x.ContractImportMode
	}
	return ContractImportMode_CONTRACT_IMPORT_MODE_UNSPECIFIED
}

func (x *ImportPartyAcsRequest) GetRepresentativePackageIdOverride() *RepresentativePackageIdOverride {
	if x != nil {
		return x.RepresentativePackageIdOverride
	}
	return nil
}

func (x *ImportPartyAcsRequest) GetPartyId() string {
	if x != nil && x.PartyId != nil {
		return *x.PartyId
	}
	return ""
}

type ImportPartyAcsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportPartyAcsResponse) Reset() {
	*x = ImportPartyAcsResponse{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportPartyAcsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportPartyAcsResponse) ProtoMessage() {}

func (x *ImportPartyAcsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportPartyAcsResponse.ProtoReflect.Descriptor instead.
func (*ImportPartyAcsResponse) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{11}
}

// Requests the highest ledger offset among all events belonging to the synchronizer
// (`synchronizer_id`) that have a record time before or at the given `timestamp`.
//
// This endpoint features a `force` message field. This is intended for disaster
// recovery scenarios only.
type GetHighestOffsetByTimestampRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the synchronizer.
	// Required
	SynchronizerId string `protobuf:"bytes,1,opt,name=synchronizer_id,json=synchronizerId,proto3" json:"synchronizer_id,omitempty"`
	// The requested timestamp for which a ledger offset should be found.
	// Required
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// When set, returns the highest known ledger offset with a record time before or at
	// the specified `timestamp`, even if higher offsets with a record time before or at
	// `timestamp` can be created in the future. Additionally, if the requested timestamp
	// is in the future, the current ledger end is safely returned.
	// Required, defaults to false.
	Force         bool `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHighestOffsetByTimestampRequest) Reset() {
	*x = GetHighestOffsetByTimestampRequest{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHighestOffsetByTimestampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHighestOffsetByTimestampRequest) ProtoMessage() {}

func (x *GetHighestOffsetByTimestampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHighestOffsetByTimestampRequest.ProtoReflect.Descriptor instead.
func (*GetHighestOffsetByTimestampRequest) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetHighestOffsetByTimestampRequest) GetSynchronizerId() string {
	if x != nil {
		return x.SynchronizerId
	}
	return ""
}

func (x *GetHighestOffsetByTimestampRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetHighestOffsetByTimestampRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type GetHighestOffsetByTimestampResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The highest ledger offset among events that have their record time before or at
	// the requested timestamp. Returns an error when no such offset (yet) exists.
	// Required
	LedgerOffset  int64 `protobuf:"varint,1,opt,name=ledger_offset,json=ledgerOffset,proto3" json:"ledger_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHighestOffsetByTimestampResponse) Reset() {
	*x = GetHighestOffsetByTimestampResponse{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHighestOffsetByTimestampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHighestOffsetByTimestampResponse) ProtoMessage() {}

func (x *GetHighestOffsetByTimestampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHighestOffsetByTimestampResponse.ProtoReflect.Descriptor instead.
func (*GetHighestOffsetByTimestampResponse) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetHighestOffsetByTimestampResponse) GetLedgerOffset() int64 {
	if x != nil {
		return x.LedgerOffset
	}
	return 0
}

// Request to clear the 'onboarding' flag for a party.
//
// The participant uses the `begin_offset_exclusive` and `wait_for_activation_timeout` to find the
// effective timestamp of the topology transaction that set the `onboarding = true` flag.
//
// This effective timestamp serves as the "lower bound" for calculating the "latest decision deadline"
// which determines the earliest safe time to clear the flag.
type ClearPartyOnboardingFlagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the party whose onboarding flag is being cleared. This party must
	// already be active on the target participant.
	// Required
	PartyId string `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// The identifier of the synchronizer.
	// Required
	SynchronizerId string `protobuf:"bytes,2,opt,name=synchronizer_id,json=synchronizerId,proto3" json:"synchronizer_id,omitempty"`
	// The exclusive ledger offset used as a starting point to find the party's most
	// recent activation on the target participant.
	// Required
	BeginOffsetExclusive int64 `protobuf:"varint,3,opt,name=begin_offset_exclusive,json=beginOffsetExclusive,proto3" json:"begin_offset_exclusive,omitempty"`
	// The maximum duration the service will wait to find the topology transaction
	// that activates the party.
	// If not set, the service will use a default timeout.
	// Optional
	WaitForActivationTimeout *durationpb.Duration `protobuf:"bytes,4,opt,name=wait_for_activation_timeout,json=waitForActivationTimeout,proto3" json:"wait_for_activation_timeout,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ClearPartyOnboardingFlagRequest) Reset() {
	*x = ClearPartyOnboardingFlagRequest{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearPartyOnboardingFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearPartyOnboardingFlagRequest) ProtoMessage() {}

func (x *ClearPartyOnboardingFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearPartyOnboardingFlagRequest.ProtoReflect.Descriptor instead.
func (*ClearPartyOnboardingFlagRequest) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{14}
}

func (x *ClearPartyOnboardingFlagRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *ClearPartyOnboardingFlagRequest) GetSynchronizerId() string {
	if x != nil {
		return x.SynchronizerId
	}
	return ""
}

func (x *ClearPartyOnboardingFlagRequest) GetBeginOffsetExclusive() int64 {
	if x != nil {
		return x.BeginOffsetExclusive
	}
	return 0
}

func (x *ClearPartyOnboardingFlagRequest) GetWaitForActivationTimeout() *durationpb.Duration {
	if x != nil {
		return x.WaitForActivationTimeout
	}
	return nil
}

// Responds with the current status of the onboarding flag:
//
// - Cleared: (true, None) – The flag is successfully cleared.
//
//   - Pending: (false, Some(timestamp)) – The flag is still set. The timestamp indicates
//     the earliest safe time to clear the flag.
//     Calling the service (repeatedly) after that specific time will eventually confirm
//     that the onboarding flag has been cleared (that is `onboarded = true`).
//
//     The onboarding flag remains for two reasons:
//     1. The safe time to clear the flag has not yet been reached.
//     2. The clearing transaction was proposed, but it has not yet become effective.
type ClearPartyOnboardingFlagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates the current party onboarding status.
	// Required
	Onboarded bool `protobuf:"varint,1,opt,name=onboarded,proto3" json:"onboarded,omitempty"`
	// The earliest time for the safe clearance of the onboarding flag.
	//
	// This field is only present when `onboarded` is `false`. It represents the
	// computed "latest decision deadline", which is the maximum of all `validUntil + decisionTimeout`
	// from the synchronizer's parameter history, ensuring all past in-flight transactions are finalized.
	EarliestRetryTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=earliest_retry_timestamp,json=earliestRetryTimestamp,proto3,oneof" json:"earliest_retry_timestamp,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ClearPartyOnboardingFlagResponse) Reset() {
	*x = ClearPartyOnboardingFlagResponse{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearPartyOnboardingFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearPartyOnboardingFlagResponse) ProtoMessage() {}

func (x *ClearPartyOnboardingFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearPartyOnboardingFlagResponse.ProtoReflect.Descriptor instead.
func (*ClearPartyOnboardingFlagResponse) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{15}
}

func (x *ClearPartyOnboardingFlagResponse) GetOnboarded() bool {
	if x != nil {
		return x.Onboarded
	}
	return false
}

func (x *ClearPartyOnboardingFlagResponse) GetEarliestRetryTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.EarliestRetryTimestamp
	}
	return nil
}

// Static parameters that do not change throughout a single party replication operation.
type PartyReplicationStatus_ReplicationParameters struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RequestId            string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PartyId              string                 `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	SynchronizerId       string                 `protobuf:"bytes,3,opt,name=synchronizer_id,json=synchronizerId,proto3" json:"synchronizer_id,omitempty"`
	SourceParticipantUid string                 `protobuf:"bytes,4,opt,name=source_participant_uid,json=sourceParticipantUid,proto3" json:"source_participant_uid,omitempty"`
	TargetParticipantUid string                 `protobuf:"bytes,5,opt,name=target_participant_uid,json=targetParticipantUid,proto3" json:"target_participant_uid,omitempty"`
	TopologySerial       uint32                 `protobuf:"varint,6,opt,name=topology_serial,json=topologySerial,proto3" json:"topology_serial,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PartyReplicationStatus_ReplicationParameters) Reset() {
	*x = PartyReplicationStatus_ReplicationParameters{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyReplicationStatus_ReplicationParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyReplicationStatus_ReplicationParameters) ProtoMessage() {}

func (x *PartyReplicationStatus_ReplicationParameters) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyReplicationStatus_ReplicationParameters.ProtoReflect.Descriptor instead.
func (*PartyReplicationStatus_ReplicationParameters) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{7, 0}
}

func (x *PartyReplicationStatus_ReplicationParameters) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PartyReplicationStatus_ReplicationParameters) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartyReplicationStatus_ReplicationParameters) GetSynchronizerId() string {
	if x != nil {
		return x.SynchronizerId
	}
	return ""
}

func (x *PartyReplicationStatus_ReplicationParameters) GetSourceParticipantUid() string {
	if x != nil {
		return x.SourceParticipantUid
	}
	return ""
}

func (x *PartyReplicationStatus_ReplicationParameters) GetTargetParticipantUid() string {
	if x != nil {
		return x.TargetParticipantUid
	}
	return ""
}

func (x *PartyReplicationStatus_ReplicationParameters) GetTopologySerial() uint32 {
	if x != nil {
		return x.TopologySerial
	}
	return 0
}

// Agreement among participants to replicate the ACS via sequencer channel.
type PartyReplicationStatus_SequencerChannelAgreement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sequencer hosting the channel for ACS replication.
	SequencerUid  string `protobuf:"bytes,1,opt,name=sequencer_uid,json=sequencerUid,proto3" json:"sequencer_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyReplicationStatus_SequencerChannelAgreement) Reset() {
	*x = PartyReplicationStatus_SequencerChannelAgreement{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyReplicationStatus_SequencerChannelAgreement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyReplicationStatus_SequencerChannelAgreement) ProtoMessage() {}

func (x *PartyReplicationStatus_SequencerChannelAgreement) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyReplicationStatus_SequencerChannelAgreement.ProtoReflect.Descriptor instead.
func (*PartyReplicationStatus_SequencerChannelAgreement) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{7, 1}
}

func (x *PartyReplicationStatus_SequencerChannelAgreement) GetSequencerUid() string {
	if x != nil {
		return x.SequencerUid
	}
	return ""
}

// Authorization by party owners and target participant to onboard the party.
type PartyReplicationStatus_PartyReplicationAuthorization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The timestamp at which the party onboarding authorization becomes effective
	// and the ACS snapshot for replication is based on.
	// required
	OnboardingAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=onboarding_at,json=onboardingAt,proto3" json:"onboarding_at,omitempty"`
	// Whether the party is fully onboarded to the target participant.
	// A value of true means:
	// - The party's ACS has been completely replicated to the target participant, and
	// - the party participates in Daml transactions according to its target participant hosting permission.
	// required
	IsOnboardingFlagCleared bool `protobuf:"varint,2,opt,name=is_onboarding_flag_cleared,json=isOnboardingFlagCleared,proto3" json:"is_onboarding_flag_cleared,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PartyReplicationStatus_PartyReplicationAuthorization) Reset() {
	*x = PartyReplicationStatus_PartyReplicationAuthorization{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyReplicationStatus_PartyReplicationAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyReplicationStatus_PartyReplicationAuthorization) ProtoMessage() {}

func (x *PartyReplicationStatus_PartyReplicationAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyReplicationStatus_PartyReplicationAuthorization.ProtoReflect.Descriptor instead.
func (*PartyReplicationStatus_PartyReplicationAuthorization) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{7, 2}
}

func (x *PartyReplicationStatus_PartyReplicationAuthorization) GetOnboardingAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OnboardingAt
	}
	return nil
}

func (x *PartyReplicationStatus_PartyReplicationAuthorization) GetIsOnboardingFlagCleared() bool {
	if x != nil {
		return x.IsOnboardingFlagCleared
	}
	return false
}

// Progress of ACS replication.
type PartyReplicationStatus_AcsReplicationProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Non negative number of ACS contracts sent by the source or persisted by the target participant.
	// required
	ProcessedContractCount uint64 `protobuf:"varint,1,opt,name=processed_contract_count,json=processedContractCount,proto3" json:"processed_contract_count,omitempty"`
	// Whether replication has been fully processed the ACS.
	// required
	FullyProcessedAcs bool `protobuf:"varint,2,opt,name=fully_processed_acs,json=fullyProcessedAcs,proto3" json:"fully_processed_acs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PartyReplicationStatus_AcsReplicationProgress) Reset() {
	*x = PartyReplicationStatus_AcsReplicationProgress{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyReplicationStatus_AcsReplicationProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyReplicationStatus_AcsReplicationProgress) ProtoMessage() {}

func (x *PartyReplicationStatus_AcsReplicationProgress) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyReplicationStatus_AcsReplicationProgress.ProtoReflect.Descriptor instead.
func (*PartyReplicationStatus_AcsReplicationProgress) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{7, 3}
}

func (x *PartyReplicationStatus_AcsReplicationProgress) GetProcessedContractCount() uint64 {
	if x != nil {
		return x.ProcessedContractCount
	}
	return 0
}

func (x *PartyReplicationStatus_AcsReplicationProgress) GetFullyProcessedAcs() bool {
	if x != nil {
		return x.FullyProcessedAcs
	}
	return false
}

// Progress of ACS indexing the Ledger Api.
type PartyReplicationStatus_AcsIndexingProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyReplicationStatus_AcsIndexingProgress) Reset() {
	*x = PartyReplicationStatus_AcsIndexingProgress{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyReplicationStatus_AcsIndexingProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyReplicationStatus_AcsIndexingProgress) ProtoMessage() {}

func (x *PartyReplicationStatus_AcsIndexingProgress) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyReplicationStatus_AcsIndexingProgress.ProtoReflect.Descriptor instead.
func (*PartyReplicationStatus_AcsIndexingProgress) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{7, 4}
}

// Error message when disconnected or operator intervention needed.
type PartyReplicationStatus_PartyReplicationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error message.
	// required
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyReplicationStatus_PartyReplicationError) Reset() {
	*x = PartyReplicationStatus_PartyReplicationError{}
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyReplicationStatus_PartyReplicationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyReplicationStatus_PartyReplicationError) ProtoMessage() {}

func (x *PartyReplicationStatus_PartyReplicationError) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyReplicationStatus_PartyReplicationError.ProtoReflect.Descriptor instead.
func (*PartyReplicationStatus_PartyReplicationError) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP(), []int{7, 5}
}

func (x *PartyReplicationStatus_PartyReplicationError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_com_digitalasset_canton_admin_participant_v30_party_management_service_proto protoreflect.FileDescriptor

const file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDesc = "" +
	"\n" +
	"Lcom/digitalasset/canton/admin/participant/v30/party_management_service.proto\x12-com.digitalasset.canton.admin.participant.v30\x1a>com/digitalasset/canton/admin/participant/v30/acs_import.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"v\n" +
	"\x14AddPartyAsyncRequest\x12^\n" +
	"\targuments\x18\x01 \x01(\v2@.com.digitalasset.canton.admin.participant.v30.AddPartyArgumentsR\targuments\"\xb3\x02\n" +
	"\x11AddPartyArguments\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12'\n" +
	"\x0fsynchronizer_id\x18\x02 \x01(\tR\x0esynchronizerId\x124\n" +
	"\x16source_participant_uid\x18\x03 \x01(\tR\x14sourceParticipantUid\x12'\n" +
	"\x0ftopology_serial\x18\x04 \x01(\rR\x0etopologySerial\x12{\n" +
	"\x16participant_permission\x18\x05 \x01(\x0e2D.com.digitalasset.canton.admin.participant.v30.ParticipantPermissionR\x15participantPermission\"H\n" +
	"\x15AddPartyAsyncResponse\x12/\n" +
	"\x14add_party_request_id\x18\x01 \x01(\tR\x11addPartyRequestId\"\xa0\x01\n" +
	"\x1bAddPartyWithAcsAsyncRequest\x12!\n" +
	"\facs_snapshot\x18\x01 \x01(\fR\vacsSnapshot\x12^\n" +
	"\targuments\x18\x02 \x01(\v2@.com.digitalasset.canton.admin.participant.v30.AddPartyArgumentsR\targuments\"O\n" +
	"\x1cAddPartyWithAcsAsyncResponse\x12/\n" +
	"\x14add_party_request_id\x18\x01 \x01(\tR\x11addPartyRequestId\"K\n" +
	"\x18GetAddPartyStatusRequest\x12/\n" +
	"\x14add_party_request_id\x18\x01 \x01(\tR\x11addPartyRequestId\"z\n" +
	"\x19GetAddPartyStatusResponse\x12]\n" +
	"\x06status\x18\x01 \x01(\v2E.com.digitalasset.canton.admin.participant.v30.PartyReplicationStatusR\x06status\"\x8d\f\n" +
	"\x16PartyReplicationStatus\x12{\n" +
	"\n" +
	"parameters\x18\x01 \x01(\v2[.com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.ReplicationParametersR\n" +
	"parameters\x12}\n" +
	"\tagreement\x18\x02 \x01(\v2_.com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.SequencerChannelAgreementR\tagreement\x12\x89\x01\n" +
	"\rauthorization\x18\x03 \x01(\v2c.com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.PartyReplicationAuthorizationR\rauthorization\x12~\n" +
	"\vreplication\x18\x04 \x01(\v2\\.com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.AcsReplicationProgressR\vreplication\x12u\n" +
	"\bindexing\x18\x05 \x01(\v2Y.com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.AcsIndexingProgressR\bindexing\x12#\n" +
	"\rhas_completed\x18\x06 \x01(\bR\fhasCompleted\x12\x80\x01\n" +
	"\rerror_message\x18\a \x01(\v2[.com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.PartyReplicationErrorR\ferrorMessage\x1a\x8f\x02\n" +
	"\x15ReplicationParameters\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bparty_id\x18\x02 \x01(\tR\apartyId\x12'\n" +
	"\x0fsynchronizer_id\x18\x03 \x01(\tR\x0esynchronizerId\x124\n" +
	"\x16source_participant_uid\x18\x04 \x01(\tR\x14sourceParticipantUid\x124\n" +
	"\x16target_participant_uid\x18\x05 \x01(\tR\x14targetParticipantUid\x12'\n" +
	"\x0ftopology_serial\x18\x06 \x01(\rR\x0etopologySerial\x1a@\n" +
	"\x19SequencerChannelAgreement\x12#\n" +
	"\rsequencer_uid\x18\x01 \x01(\tR\fsequencerUid\x1a\x9d\x01\n" +
	"\x1dPartyReplicationAuthorization\x12?\n" +
	"\ronboarding_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\fonboardingAt\x12;\n" +
	"\x1ais_onboarding_flag_cleared\x18\x02 \x01(\bR\x17isOnboardingFlagCleared\x1a\x82\x01\n" +
	"\x16AcsReplicationProgress\x128\n" +
	"\x18processed_contract_count\x18\x01 \x01(\x04R\x16processedContractCount\x12.\n" +
	"\x13fully_processed_acs\x18\x02 \x01(\bR\x11fullyProcessedAcs\x1a\x15\n" +
	"\x13AcsIndexingProgress\x1a<\n" +
	"\x15PartyReplicationError\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xa1\x02\n" +
	"\x15ExportPartyAcsRequest\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12'\n" +
	"\x0fsynchronizer_id\x18\x02 \x01(\tR\x0esynchronizerId\x124\n" +
	"\x16target_participant_uid\x18\x03 \x01(\tR\x14targetParticipantUid\x124\n" +
	"\x16begin_offset_exclusive\x18\x04 \x01(\x03R\x14beginOffsetExclusive\x12X\n" +
	"\x1bwait_for_activation_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x18waitForActivationTimeout\".\n" +
	"\x16ExportPartyAcsResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"\xd0\x04\n" +
	"\x15ImportPartyAcsRequest\x12!\n" +
	"\facs_snapshot\x18\x01 \x01(\fR\vacsSnapshot\x12,\n" +
	"\x0fsynchronizer_id\x18\x02 \x01(\tH\x00R\x0esynchronizerId\x88\x01\x01\x121\n" +
	"\x12workflow_id_prefix\x18\x03 \x01(\tH\x01R\x10workflowIdPrefix\x88\x01\x01\x12x\n" +
	"\x14contract_import_mode\x18\x04 \x01(\x0e2A.com.digitalasset.canton.admin.participant.v30.ContractImportModeH\x02R\x12contractImportMode\x88\x01\x01\x12\xa0\x01\n" +
	"\"representative_package_id_override\x18\x05 \x01(\v2N.com.digitalasset.canton.admin.participant.v30.RepresentativePackageIdOverrideH\x03R\x1frepresentativePackageIdOverride\x88\x01\x01\x12\x1e\n" +
	"\bparty_id\x18\x06 \x01(\tH\x04R\apartyId\x88\x01\x01B\x12\n" +
	"\x10_synchronizer_idB\x15\n" +
	"\x13_workflow_id_prefixB\x17\n" +
	"\x15_contract_import_modeB%\n" +
	"#_representative_package_id_overrideB\v\n" +
	"\t_party_id\"\x18\n" +
	"\x16ImportPartyAcsResponse\"\x9d\x01\n" +
	"\"GetHighestOffsetByTimestampRequest\x12'\n" +
	"\x0fsynchronizer_id\x18\x01 \x01(\tR\x0esynchronizerId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"J\n" +
	"#GetHighestOffsetByTimestampResponse\x12#\n" +
	"\rledger_offset\x18\x01 \x01(\x03R\fledgerOffset\"\xf5\x01\n" +
	"\x1fClearPartyOnboardingFlagRequest\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12'\n" +
	"\x0fsynchronizer_id\x18\x02 \x01(\tR\x0esynchronizerId\x124\n" +
	"\x16begin_offset_exclusive\x18\x03 \x01(\x03R\x14beginOffsetExclusive\x12X\n" +
	"\x1bwait_for_activation_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x18waitForActivationTimeout\"\xb8\x01\n" +
	" ClearPartyOnboardingFlagResponse\x12\x1c\n" +
	"\tonboarded\x18\x01 \x01(\bR\tonboarded\x12Y\n" +
	"\x18earliest_retry_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x16earliestRetryTimestamp\x88\x01\x01B\x1b\n" +
	"\x19_earliest_retry_timestamp*\xb7\x01\n" +
	"\x15ParticipantPermission\x12&\n" +
	"\"PARTICIPANT_PERMISSION_UNSPECIFIED\x10\x00\x12%\n" +
	"!PARTICIPANT_PERMISSION_SUBMISSION\x10\x01\x12'\n" +
	"#PARTICIPANT_PERMISSION_CONFIRMATION\x10\x02\x12&\n" +
	"\"PARTICIPANT_PERMISSION_OBSERVATION\x10\x032\xdb\t\n" +
	"\x16PartyManagementService\x12\x9a\x01\n" +
	"\rAddPartyAsync\x12C.com.digitalasset.canton.admin.participant.v30.AddPartyAsyncRequest\x1aD.com.digitalasset.canton.admin.participant.v30.AddPartyAsyncResponse\x12\xb1\x01\n" +
	"\x14AddPartyWithAcsAsync\x12J.com.digitalasset.canton.admin.participant.v30.AddPartyWithAcsAsyncRequest\x1aK.com.digitalasset.canton.admin.participant.v30.AddPartyWithAcsAsyncResponse(\x01\x12\xa6\x01\n" +
	"\x11GetAddPartyStatus\x12G.com.digitalasset.canton.admin.participant.v30.GetAddPartyStatusRequest\x1aH.com.digitalasset.canton.admin.participant.v30.GetAddPartyStatusResponse\x12\x9f\x01\n" +
	"\x0eExportPartyAcs\x12D.com.digitalasset.canton.admin.participant.v30.ExportPartyAcsRequest\x1aE.com.digitalasset.canton.admin.participant.v30.ExportPartyAcsResponse0\x01\x12\x9f\x01\n" +
	"\x0eImportPartyAcs\x12D.com.digitalasset.canton.admin.participant.v30.ImportPartyAcsRequest\x1aE.com.digitalasset.canton.admin.participant.v30.ImportPartyAcsResponse(\x01\x12\xc4\x01\n" +
	"\x1bGetHighestOffsetByTimestamp\x12Q.com.digitalasset.canton.admin.participant.v30.GetHighestOffsetByTimestampRequest\x1aR.com.digitalasset.canton.admin.participant.v30.GetHighestOffsetByTimestampResponse\x12\xbb\x01\n" +
	"\x18ClearPartyOnboardingFlag\x12N.com.digitalasset.canton.admin.participant.v30.ClearPartyOnboardingFlagRequest\x1aO.com.digitalasset.canton.admin.participant.v30.ClearPartyOnboardingFlagResponseBTZRgithub.com/noders-team/go-daml/proto/com/digitalasset/canton/admin/participant/v30b\x06proto3"

var (
	file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescOnce sync.Once
	file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescData []byte
)

func file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescGZIP() []byte {
	file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescOnce.Do(func() {
		file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDesc), len(file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDesc)))
	})
	return file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDescData
}

var file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_goTypes = []any{
	(ParticipantPermission)(0),                                   // 0: com.digitalasset.canton.admin.participant.v30.ParticipantPermission
	(*AddPartyAsyncRequest)(nil),                                 // 1: com.digitalasset.canton.admin.participant.v30.AddPartyAsyncRequest
	(*AddPartyArguments)(nil),                                    // 2: com.digitalasset.canton.admin.participant.v30.AddPartyArguments
	(*AddPartyAsyncResponse)(nil),                                // 3: com.digitalasset.canton.admin.participant.v30.AddPartyAsyncResponse
	(*AddPartyWithAcsAsyncRequest)(nil),                          // 4: com.digitalasset.canton.admin.participant.v30.AddPartyWithAcsAsyncRequest
	(*AddPartyWithAcsAsyncResponse)(nil),                         // 5: com.digitalasset.canton.admin.participant.v30.AddPartyWithAcsAsyncResponse
	(*GetAddPartyStatusRequest)(nil),                             // 6: com.digitalasset.canton.admin.participant.v30.GetAddPartyStatusRequest
	(*GetAddPartyStatusResponse)(nil),                            // 7: com.digitalasset.canton.admin.participant.v30.GetAddPartyStatusResponse
	(*PartyReplicationStatus)(nil),                               // 8: com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus
	(*ExportPartyAcsRequest)(nil),                                // 9: com.digitalasset.canton.admin.participant.v30.ExportPartyAcsRequest
	(*ExportPartyAcsResponse)(nil),                               // 10: com.digitalasset.canton.admin.participant.v30.ExportPartyAcsResponse
	(*ImportPartyAcsRequest)(nil),                                // 11: com.digitalasset.canton.admin.participant.v30.ImportPartyAcsRequest
	(*ImportPartyAcsResponse)(nil),                               // 12: com.digitalasset.canton.admin.participant.v30.ImportPartyAcsResponse
	(*GetHighestOffsetByTimestampRequest)(nil),                   // 13: com.digitalasset.canton.admin.participant.v30.GetHighestOffsetByTimestampRequest
	(*GetHighestOffsetByTimestampResponse)(nil),                  // 14: com.digitalasset.canton.admin.participant.v30.GetHighestOffsetByTimestampResponse
	(*ClearPartyOnboardingFlagRequest)(nil),                      // 15: com.digitalasset.canton.admin.participant.v30.ClearPartyOnboardingFlagRequest
	(*ClearPartyOnboardingFlagResponse)(nil),                     // 16: com.digitalasset.canton.admin.participant.v30.ClearPartyOnboardingFlagResponse
	(*PartyReplicationStatus_ReplicationParameters)(nil),         // 17: com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.ReplicationParameters
	(*PartyReplicationStatus_SequencerChannelAgreement)(nil),     // 18: com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.SequencerChannelAgreement
	(*PartyReplicationStatus_PartyReplicationAuthorization)(nil), // 19: com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.PartyReplicationAuthorization
	(*PartyReplicationStatus_AcsReplicationProgress)(nil),        // 20: com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.AcsReplicationProgress
	(*PartyReplicationStatus_AcsIndexingProgress)(nil),           // 21: com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.AcsIndexingProgress
	(*PartyReplicationStatus_PartyReplicationError)(nil),         // 22: com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.PartyReplicationError
	(*durationpb.Duration)(nil),                                  // 23: google.protobuf.Duration
	(ContractImportMode)(0),                                      // 24: com.digitalasset.canton.admin.participant.v30.ContractImportMode
	(*RepresentativePackageIdOverride)(nil),                      // 25: com.digitalasset.canton.admin.participant.v30.RepresentativePackageIdOverride
	(*timestamppb.Timestamp)(nil),                                // 26: google.protobuf.Timestamp
}
var file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_depIdxs = []int32{
	2,  // 0: com.digitalasset.canton.admin.participant.v30.AddPartyAsyncRequest.arguments:type_name -> com.digitalasset.canton.admin.participant.v30.AddPartyArguments
	0,  // 1: com.digitalasset.canton.admin.participant.v30.AddPartyArguments.participant_permission:type_name -> com.digitalasset.canton.admin.participant.v30.ParticipantPermission
	2,  // 2: com.digitalasset.canton.admin.participant.v30.AddPartyWithAcsAsyncRequest.arguments:type_name -> com.digitalasset.canton.admin.participant.v30.AddPartyArguments
	8,  // 3: com.digitalasset.canton.admin.participant.v30.GetAddPartyStatusResponse.status:type_name -> com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus
	17, // 4: com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.parameters:type_name -> com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.ReplicationParameters
	18, // 5: com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.agreement:type_name -> com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.SequencerChannelAgreement
	19, // 6: com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.authorization:type_name -> com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.PartyReplicationAuthorization
	20, // 7: com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.replication:type_name -> com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.AcsReplicationProgress
	21, // 8: com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.indexing:type_name -> com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.AcsIndexingProgress
	22, // 9: com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.error_message:type_name -> com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.PartyReplicationError
	23, // 10: com.digitalasset.canton.admin.participant.v30.ExportPartyAcsRequest.wait_for_activation_timeout:type_name -> google.protobuf.Duration
	24, // 11: com.digitalasset.canton.admin.participant.v30.ImportPartyAcsRequest.contract_import_mode:type_name -> com.digitalasset.canton.admin.participant.v30.ContractImportMode
	25, // 12: com.digitalasset.canton.admin.participant.v30.ImportPartyAcsRequest.representative_package_id_override:type_name -> com.digitalasset.canton.admin.participant.v30.RepresentativePackageIdOverride
	26, // 13: com.digitalasset.canton.admin.participant.v30.GetHighestOffsetByTimestampRequest.timestamp:type_name -> google.protobuf.Timestamp
	23, // 14: com.digitalasset.canton.admin.participant.v30.ClearPartyOnboardingFlagRequest.wait_for_activation_timeout:type_name -> google.protobuf.Duration
	26, // 15: com.digitalasset.canton.admin.participant.v30.ClearPartyOnboardingFlagResponse.earliest_retry_timestamp:type_name -> google.protobuf.Timestamp
	26, // 16: com.digitalasset.canton.admin.participant.v30.PartyReplicationStatus.PartyReplicationAuthorization.onboarding_at:type_name -> google.protobuf.Timestamp
	1,  // 17: com.digitalasset.canton.admin.participant.v30.PartyManagementService.AddPartyAsync:input_type -> com.digitalasset.canton.admin.participant.v30.AddPartyAsyncRequest
	4,  // 18: com.digitalasset.canton.admin.participant.v30.PartyManagementService.AddPartyWithAcsAsync:input_type -> com.digitalasset.canton.admin.participant.v30.AddPartyWithAcsAsyncRequest
	6,  // 19: com.digitalasset.canton.admin.participant.v30.PartyManagementService.GetAddPartyStatus:input_type -> com.digitalasset.canton.admin.participant.v30.GetAddPartyStatusRequest
	9,  // 20: com.digitalasset.canton.admin.participant.v30.PartyManagementService.ExportPartyAcs:input_type -> com.digitalasset.canton.admin.participant.v30.ExportPartyAcsRequest
	11, // 21: com.digitalasset.canton.admin.participant.v30.PartyManagementService.ImportPartyAcs:input_type -> com.digitalasset.canton.admin.participant.v30.ImportPartyAcsRequest
	13, // 22: com.digitalasset.canton.admin.participant.v30.PartyManagementService.GetHighestOffsetByTimestamp:input_type -> com.digitalasset.canton.admin.participant.v30.GetHighestOffsetByTimestampRequest
	15, // 23: com.digitalasset.canton.admin.participant.v30.PartyManagementService.ClearPartyOnboardingFlag:input_type -> com.digitalasset.canton.admin.participant.v30.ClearPartyOnboardingFlagRequest
	3,  // 24: com.digitalasset.canton.admin.participant.v30.PartyManagementService.AddPartyAsync:output_type -> com.digitalasset.canton.admin.participant.v30.AddPartyAsyncResponse
	5,  // 25: com.digitalasset.canton.admin.participant.v30.PartyManagementService.AddPartyWithAcsAsync:output_type -> com.digitalasset.canton.admin.participant.v30.AddPartyWithAcsAsyncResponse
	7,  // 26: com.digitalasset.canton.admin.participant.v30.PartyManagementService.GetAddPartyStatus:output_type -> com.digitalasset.canton.admin.participant.v30.GetAddPartyStatusResponse
	10, // 27: com.digitalasset.canton.admin.participant.v30.PartyManagementService.ExportPartyAcs:output_type -> com.digitalasset.canton.admin.participant.v30.ExportPartyAcsResponse
	12, // 28: com.digitalasset.canton.admin.participant.v30.PartyManagementService.ImportPartyAcs:output_type -> com.digitalasset.canton.admin.participant.v30.ImportPartyAcsResponse
	14, // 29: com.digitalasset.canton.admin.participant.v30.PartyManagementService.GetHighestOffsetByTimestamp:output_type -> com.digitalasset.canton.admin.participant.v30.GetHighestOffsetByTimestampResponse
	16, // 30: com.digitalasset.canton.admin.participant.v30.PartyManagementService.ClearPartyOnboardingFlag:output_type -> com.digitalasset.canton.admin.participant.v30.ClearPartyOnboardingFlagResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_init() }
func file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_init() {
	if File_com_digitalasset_canton_admin_participant_v30_party_management_service_proto != nil {
		return
	}
	file_com_digitalasset_canton_admin_participant_v30_acs_import_proto_init()
	file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDesc), len(file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_goTypes,
		DependencyIndexes: file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_depIdxs,
		EnumInfos:         file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_enumTypes,
		MessageInfos:      file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_msgTypes,
	}.Build()
	File_com_digitalasset_canton_admin_participant_v30_party_management_service_proto = out.File
	file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_goTypes = nil
	file_com_digitalasset_canton_admin_participant_v30_party_management_service_proto_depIdxs = nil
}
