#!/usr/bin/env bash
set -euo pipefail

# Generates Go gRPC/protobuf bindings for the DAML/Canton Ledger API into this
# package. Mirrors the dazl-client protopack pipeline (download Canton release ->
# patch protos with go_package -> protoc) without Nix or Python.
#
# Requirements on PATH: protoc, protoc-gen-go, protoc-gen-go-grpc.

CANTON_VERSION="${CANTON_VERSION:-3.5.1-rc5}"
GO_MODULE="github.com/noders-team/go-daml/proto"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cache_dir="${PROTO_CACHE_DIR:-$script_dir/.cache}"
tarball="$cache_dir/canton-open-source-$CANTON_VERSION.tar.gz"
url="https://github.com/digital-asset/canton/releases/download/v$CANTON_VERSION/canton-open-source-$CANTON_VERSION.tar.gz"

for bin in protoc protoc-gen-go protoc-gen-go-grpc; do
  command -v "$bin" >/dev/null 2>&1 || { echo "error: $bin not found on PATH" >&2; exit 1; }
done

mkdir -p "$cache_dir"
if [ ! -f "$tarball" ]; then
  echo "Downloading $url"
  curl -fL -o "$tarball" "$url"
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "Extracting protobuf sources"
tar xzf "$tarball" -C "$work" --strip-components=1 "canton-open-source-$CANTON_VERSION/protobuf"
src="$work/protobuf"

protos="$work/protos"
libs="$work/lib"
mkdir -p "$protos" "$libs"
cp -R "$src/lib/." "$libs/"

# Copy each API bundle into a single merged tree, dropping scalapb references and
# injecting an `option go_package` derived from the file's directory path. The
# daml-lf archive protos share one directory but declare three distinct packages,
# so they are split into sub-packages to keep one Go package per directory.
for bundle in admin-api archive community ledger-api ledger-api-value participant synchronizer transaction; do
  while IFS= read -r f; do
    rel="${f#$src/$bundle/}"
    dir="$(dirname "$rel")"
    case "$rel" in
      com/digitalasset/daml/lf/archive/daml_lf.proto)  gp="$GO_MODULE/$dir;daml_lf" ;;
      com/digitalasset/daml/lf/archive/daml_lf1.proto) gp="$GO_MODULE/$dir/daml_lf_1" ;;
      com/digitalasset/daml/lf/archive/daml_lf2.proto) gp="$GO_MODULE/$dir/daml_lf_2" ;;
      com/daml/ledger/api/v2/interactive/interactive_submission_common_data.proto) gp="$GO_MODULE/$dir/common" ;;
      *) gp="$GO_MODULE/$dir" ;;
    esac
    mkdir -p "$protos/$dir"
    awk -v gp="$gp" '
      /scalapb/ { next }
      /^package .*;$/ { print; print ""; print "option go_package = \"" gp "\";"; next }
      { print }
    ' "$f" > "$protos/$rel"
  done < <(find "$src/$bundle" -type f -name '*.proto' ! -name 'package.proto')
done

echo "Cleaning previous output"
find "$script_dir" -mindepth 1 -maxdepth 1 -type d -name 'com' -exec rm -rf {} +

echo "Running protoc"
protoc -I "$libs" -I "$protos" \
  --go_out="$script_dir" --go_opt=module="$GO_MODULE" \
  --go_opt=Mgoogle/rpc/status.proto=google.golang.org/genproto/googleapis/rpc/status \
  --go-grpc_out="$script_dir" --go-grpc_opt=module="$GO_MODULE" \
  --go-grpc_opt=Mgoogle/rpc/status.proto=google.golang.org/genproto/googleapis/rpc/status \
  $(find "$protos" -name '*.proto')

echo "Recording Canton version"
cat > "$script_dir/version.go" <<EOF
// Code generated by proto/generate.sh. DO NOT EDIT.

package proto

// CantonVersion is the digital-asset/canton open-source release whose
// protobuf definitions these Go bindings were generated from.
const CantonVersion = "$CANTON_VERSION"

// Version returns the Canton release the generated bindings were built from.
func Version() string { return CantonVersion }
EOF

echo "Generated bindings under $script_dir/com (Canton $CANTON_VERSION)"
