// Code generated by proto/generate.sh. DO NOT EDIT.

package proto

// CantonVersion is the digital-asset/canton open-source release whose
// protobuf definitions these Go bindings were generated from.
const CantonVersion = "3.5.1-rc5"

// Version returns the Canton release the generated bindings were built from.
func Version() string { return CantonVersion }
