// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: com/digitalasset/canton/sequencer/api/v30/sequencer_service.proto

package v30

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SequencerService_SendAsync_FullMethodName                        = "/com.digitalasset.canton.sequencer.api.v30.SequencerService/SendAsync"
	SequencerService_Subscribe_FullMethodName                        = "/com.digitalasset.canton.sequencer.api.v30.SequencerService/Subscribe"
	SequencerService_AcknowledgeSigned_FullMethodName                = "/com.digitalasset.canton.sequencer.api.v30.SequencerService/AcknowledgeSigned"
	SequencerService_DownloadTopologyStateForInit_FullMethodName     = "/com.digitalasset.canton.sequencer.api.v30.SequencerService/DownloadTopologyStateForInit"
	SequencerService_DownloadTopologyStateForInitHash_FullMethodName = "/com.digitalasset.canton.sequencer.api.v30.SequencerService/DownloadTopologyStateForInitHash"
	SequencerService_GetTrafficStateForMember_FullMethodName         = "/com.digitalasset.canton.sequencer.api.v30.SequencerService/GetTrafficStateForMember"
	SequencerService_GetTime_FullMethodName                          = "/com.digitalasset.canton.sequencer.api.v30.SequencerService/GetTime"
)

// SequencerServiceClient is the client API for SequencerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service that a member can use to send messages to the synchronizer and
// receive events from the synchronizer
type SequencerServiceClient interface {
	// Submit a request to the sequencer.
	//
	// A request contains a batch, which is a sequence of envelopes.
	// Every envelope consists of its content and a set of recipients, arranged in a forest.
	// A synchronizer member is intended to receive those envelopes of a batch that contain the member as a recipient.
	// A synchronizer member is supposed to learn about those recipients of an envelope that are
	// (1) specified at a node that also specifies the member or
	// (2) at a descendant thereof. (I.e., a node further down in the recipient forest.)
	//
	// The sequencer may or may not accept a request.
	// If an incoming request is valid (i.e., it can be parsed and every field meets its documented validity conditions)
	// an honest sequencer will accept requests in a best effort manner, provided resource limits are met.
	//
	// For every accepted request, the sequencer assigns a unique sequencing timestamp to the request.
	// All honest sequencers of the synchronizer will deliver an event to the sender and
	// to those synchronizer members that are intended to receive at least one envelope.
	//
	// Honest sequencers may deliver to all sequencers of the synchronizer events that don't correspond to submitted requests.
	// Sequencer implementations may leverage this mechanism for internal purposes.
	//
	// An event for a synchronizer member contains only those envelopes of the batch of the request
	// that the member is intended to receive and
	// the recipients of an envelope contains only those that the member is supposed to learn about.
	// A member will receive the envelopes of the same request within a single event.
	// A member will receive events ordered by sequencing timestamp.
	//
	// If a request is accepted, the sender will receive a corresponding event, called "receipt";
	// so that the sender is informed that the sequencer has accepted the request.
	// If the sender is not a recipient of the request, the receipt has an empty batch.
	//
	// If the request contains an aggregation rule, the sequencer will process requests in an aggregated fashion.
	// A set of requests belong to the same aggregation, if they have essentially the same contents (details specified at SubmissionRequest.aggregationId).
	// The sequencer validates and assigns sequencing timestamps to requests within an aggregation just as for requests without an aggregation rule.
	// The sequencer emits events and receipts for an accepted request within an aggregation as follows:
	//   - As long as the number of accepted requests is strictly less than AggregationRule.threshold,
	//     the sequencer only emits a receipt with an empty batch to the sender of the request.
	//     It does not emit any other events.
	//   - As soon as the number of accepted requests equals AggregationRule.threshold, the sequencer emits
	//     events to the sender and the recipients of the request.
	//     The sequencing timestamp of the events is the sequencing timestamp of the last accepted request.
	//   - The sequencer will not accept more than AggregationRule.threshold requests.
	//     The sequencer will reject any further request that could otherwise be accepted.
	//     Consequently, events for the request are delivered only once even if the threshold is attained multiple times.
	//
	// If the request does not contain an aggregation rule, even honest sequencers may deliver events for the request
	// more than once (with different sequencing timestamps), as malicious sequencers may replay a request internally.
	// Clients need to implement appropriate deduplication, if at-most-once delivery is needed.
	// Once request.max_sequencing_time has elapsed (i.e. an event with an equal or higher timestamp has been emitted),
	// an honest sequencer will not emit events corresponding to request anymore.
	//
	// The sequencer may reject a request, e.g., because the request is invalid or the sequencer is overloaded.
	// The sequencer will indicate a rejection (independently of whether there is an aggregation rule)
	// in exactly one of the following ways:
	// (1) synchronously, by returning an error in the response of this method
	// (2) asynchronously, by emitting an error in the response to SubscribeVersioned to the sender and
	//
	//	possibly an empty batch to non-sender recipients
	//
	// (3) by not emitting a receipt to the sender until request.max_sequencing_time
	// Note that only (2) and (3) can be trusted. A malicious sequencer may synchronously return an error and
	// still accept the request internally and therefore emit events later on.
	SendAsync(ctx context.Context, in *SendAsyncRequest, opts ...grpc.CallOption) (*SendAsyncResponse, error)
	// Establishes a stream with the server to receive sequenced events from the synchronizer after the given
	// counter. The delivered events will have a reference to the previous event (its timestamp)
	// and a strictly monotonically increasing timestamp.
	//
	// The call fails synchronously, if the request is invalid, i.e., some field violates a documented validity condition.
	// The call fails asynchronously, if the sequencer does not have a key to sign the event; this may occur if
	// event.topology_timestamp refers to a time before the sequencer has been onboarded.
	Subscribe(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscriptionResponse], error)
	// Allows a member to acknowledge that they have read all events up to and including the provided timestamp,
	// and that they will never re-read these events again. This information is currently only used for informational
	// purposes and to provide a watermark for which it is safe to prune earlier events from the sequencer data stores.
	// There is no requirement for every event to be individually acknowledged, and in fact callers are encouraged to
	// only periodically record acknowledgements (at an interval of minutes is expected to be more than sufficient for
	// pruning).
	AcknowledgeSigned(ctx context.Context, in *AcknowledgeSignedRequest, opts ...grpc.CallOption) (*AcknowledgeSignedResponse, error)
	// Download the topology state for a member up to including the topology transaction that made the member
	// known on the synchronizer.
	DownloadTopologyStateForInit(ctx context.Context, in *DownloadTopologyStateForInitRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadTopologyStateForInitResponse], error)
	// Returns a hash of a result equivalent to DownloadTopologyStateForInit call
	// for a BFT check without transferring the full state.
	DownloadTopologyStateForInitHash(ctx context.Context, in *DownloadTopologyStateForInitHashRequest, opts ...grpc.CallOption) (*DownloadTopologyStateForInitHashResponse, error)
	// Return the currently known traffic state for a member. Callers must be authorized to request the traffic state.
	GetTrafficStateForMember(ctx context.Context, in *GetTrafficStateForMemberRequest, opts ...grpc.CallOption) (*GetTrafficStateForMemberResponse, error)
	// Return a "current" sequencing time such that, when a `SendAsync` operation is
	// subsequently called, if sequenced, the sequencing time of the resulting event is guaranteed to
	// be later than the sequencing time previously returned by the `GetTime` call.
	GetTime(ctx context.Context, in *GetTimeRequest, opts ...grpc.CallOption) (*GetTimeResponse, error)
}

type sequencerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSequencerServiceClient(cc grpc.ClientConnInterface) SequencerServiceClient {
	return &sequencerServiceClient{cc}
}

func (c *sequencerServiceClient) SendAsync(ctx context.Context, in *SendAsyncRequest, opts ...grpc.CallOption) (*SendAsyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendAsyncResponse)
	err := c.cc.Invoke(ctx, SequencerService_SendAsync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sequencerServiceClient) Subscribe(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscriptionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SequencerService_ServiceDesc.Streams[0], SequencerService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscriptionRequest, SubscriptionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SequencerService_SubscribeClient = grpc.ServerStreamingClient[SubscriptionResponse]

func (c *sequencerServiceClient) AcknowledgeSigned(ctx context.Context, in *AcknowledgeSignedRequest, opts ...grpc.CallOption) (*AcknowledgeSignedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeSignedResponse)
	err := c.cc.Invoke(ctx, SequencerService_AcknowledgeSigned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sequencerServiceClient) DownloadTopologyStateForInit(ctx context.Context, in *DownloadTopologyStateForInitRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadTopologyStateForInitResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SequencerService_ServiceDesc.Streams[1], SequencerService_DownloadTopologyStateForInit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadTopologyStateForInitRequest, DownloadTopologyStateForInitResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SequencerService_DownloadTopologyStateForInitClient = grpc.ServerStreamingClient[DownloadTopologyStateForInitResponse]

func (c *sequencerServiceClient) DownloadTopologyStateForInitHash(ctx context.Context, in *DownloadTopologyStateForInitHashRequest, opts ...grpc.CallOption) (*DownloadTopologyStateForInitHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadTopologyStateForInitHashResponse)
	err := c.cc.Invoke(ctx, SequencerService_DownloadTopologyStateForInitHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sequencerServiceClient) GetTrafficStateForMember(ctx context.Context, in *GetTrafficStateForMemberRequest, opts ...grpc.CallOption) (*GetTrafficStateForMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrafficStateForMemberResponse)
	err := c.cc.Invoke(ctx, SequencerService_GetTrafficStateForMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sequencerServiceClient) GetTime(ctx context.Context, in *GetTimeRequest, opts ...grpc.CallOption) (*GetTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimeResponse)
	err := c.cc.Invoke(ctx, SequencerService_GetTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SequencerServiceServer is the server API for SequencerService service.
// All implementations must embed UnimplementedSequencerServiceServer
// for forward compatibility.
//
// The service that a member can use to send messages to the synchronizer and
// receive events from the synchronizer
type SequencerServiceServer interface {
	// Submit a request to the sequencer.
	//
	// A request contains a batch, which is a sequence of envelopes.
	// Every envelope consists of its content and a set of recipients, arranged in a forest.
	// A synchronizer member is intended to receive those envelopes of a batch that contain the member as a recipient.
	// A synchronizer member is supposed to learn about those recipients of an envelope that are
	// (1) specified at a node that also specifies the member or
	// (2) at a descendant thereof. (I.e., a node further down in the recipient forest.)
	//
	// The sequencer may or may not accept a request.
	// If an incoming request is valid (i.e., it can be parsed and every field meets its documented validity conditions)
	// an honest sequencer will accept requests in a best effort manner, provided resource limits are met.
	//
	// For every accepted request, the sequencer assigns a unique sequencing timestamp to the request.
	// All honest sequencers of the synchronizer will deliver an event to the sender and
	// to those synchronizer members that are intended to receive at least one envelope.
	//
	// Honest sequencers may deliver to all sequencers of the synchronizer events that don't correspond to submitted requests.
	// Sequencer implementations may leverage this mechanism for internal purposes.
	//
	// An event for a synchronizer member contains only those envelopes of the batch of the request
	// that the member is intended to receive and
	// the recipients of an envelope contains only those that the member is supposed to learn about.
	// A member will receive the envelopes of the same request within a single event.
	// A member will receive events ordered by sequencing timestamp.
	//
	// If a request is accepted, the sender will receive a corresponding event, called "receipt";
	// so that the sender is informed that the sequencer has accepted the request.
	// If the sender is not a recipient of the request, the receipt has an empty batch.
	//
	// If the request contains an aggregation rule, the sequencer will process requests in an aggregated fashion.
	// A set of requests belong to the same aggregation, if they have essentially the same contents (details specified at SubmissionRequest.aggregationId).
	// The sequencer validates and assigns sequencing timestamps to requests within an aggregation just as for requests without an aggregation rule.
	// The sequencer emits events and receipts for an accepted request within an aggregation as follows:
	//   - As long as the number of accepted requests is strictly less than AggregationRule.threshold,
	//     the sequencer only emits a receipt with an empty batch to the sender of the request.
	//     It does not emit any other events.
	//   - As soon as the number of accepted requests equals AggregationRule.threshold, the sequencer emits
	//     events to the sender and the recipients of the request.
	//     The sequencing timestamp of the events is the sequencing timestamp of the last accepted request.
	//   - The sequencer will not accept more than AggregationRule.threshold requests.
	//     The sequencer will reject any further request that could otherwise be accepted.
	//     Consequently, events for the request are delivered only once even if the threshold is attained multiple times.
	//
	// If the request does not contain an aggregation rule, even honest sequencers may deliver events for the request
	// more than once (with different sequencing timestamps), as malicious sequencers may replay a request internally.
	// Clients need to implement appropriate deduplication, if at-most-once delivery is needed.
	// Once request.max_sequencing_time has elapsed (i.e. an event with an equal or higher timestamp has been emitted),
	// an honest sequencer will not emit events corresponding to request anymore.
	//
	// The sequencer may reject a request, e.g., because the request is invalid or the sequencer is overloaded.
	// The sequencer will indicate a rejection (independently of whether there is an aggregation rule)
	// in exactly one of the following ways:
	// (1) synchronously, by returning an error in the response of this method
	// (2) asynchronously, by emitting an error in the response to SubscribeVersioned to the sender and
	//
	//	possibly an empty batch to non-sender recipients
	//
	// (3) by not emitting a receipt to the sender until request.max_sequencing_time
	// Note that only (2) and (3) can be trusted. A malicious sequencer may synchronously return an error and
	// still accept the request internally and therefore emit events later on.
	SendAsync(context.Context, *SendAsyncRequest) (*SendAsyncResponse, error)
	// Establishes a stream with the server to receive sequenced events from the synchronizer after the given
	// counter. The delivered events will have a reference to the previous event (its timestamp)
	// and a strictly monotonically increasing timestamp.
	//
	// The call fails synchronously, if the request is invalid, i.e., some field violates a documented validity condition.
	// The call fails asynchronously, if the sequencer does not have a key to sign the event; this may occur if
	// event.topology_timestamp refers to a time before the sequencer has been onboarded.
	Subscribe(*SubscriptionRequest, grpc.ServerStreamingServer[SubscriptionResponse]) error
	// Allows a member to acknowledge that they have read all events up to and including the provided timestamp,
	// and that they will never re-read these events again. This information is currently only used for informational
	// purposes and to provide a watermark for which it is safe to prune earlier events from the sequencer data stores.
	// There is no requirement for every event to be individually acknowledged, and in fact callers are encouraged to
	// only periodically record acknowledgements (at an interval of minutes is expected to be more than sufficient for
	// pruning).
	AcknowledgeSigned(context.Context, *AcknowledgeSignedRequest) (*AcknowledgeSignedResponse, error)
	// Download the topology state for a member up to including the topology transaction that made the member
	// known on the synchronizer.
	DownloadTopologyStateForInit(*DownloadTopologyStateForInitRequest, grpc.ServerStreamingServer[DownloadTopologyStateForInitResponse]) error
	// Returns a hash of a result equivalent to DownloadTopologyStateForInit call
	// for a BFT check without transferring the full state.
	DownloadTopologyStateForInitHash(context.Context, *DownloadTopologyStateForInitHashRequest) (*DownloadTopologyStateForInitHashResponse, error)
	// Return the currently known traffic state for a member. Callers must be authorized to request the traffic state.
	GetTrafficStateForMember(context.Context, *GetTrafficStateForMemberRequest) (*GetTrafficStateForMemberResponse, error)
	// Return a "current" sequencing time such that, when a `SendAsync` operation is
	// subsequently called, if sequenced, the sequencing time of the resulting event is guaranteed to
	// be later than the sequencing time previously returned by the `GetTime` call.
	GetTime(context.Context, *GetTimeRequest) (*GetTimeResponse, error)
	mustEmbedUnimplementedSequencerServiceServer()
}

// UnimplementedSequencerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSequencerServiceServer struct{}

func (UnimplementedSequencerServiceServer) SendAsync(context.Context, *SendAsyncRequest) (*SendAsyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAsync not implemented")
}
func (UnimplementedSequencerServiceServer) Subscribe(*SubscriptionRequest, grpc.ServerStreamingServer[SubscriptionResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSequencerServiceServer) AcknowledgeSigned(context.Context, *AcknowledgeSignedRequest) (*AcknowledgeSignedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeSigned not implemented")
}
func (UnimplementedSequencerServiceServer) DownloadTopologyStateForInit(*DownloadTopologyStateForInitRequest, grpc.ServerStreamingServer[DownloadTopologyStateForInitResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadTopologyStateForInit not implemented")
}
func (UnimplementedSequencerServiceServer) DownloadTopologyStateForInitHash(context.Context, *DownloadTopologyStateForInitHashRequest) (*DownloadTopologyStateForInitHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadTopologyStateForInitHash not implemented")
}
func (UnimplementedSequencerServiceServer) GetTrafficStateForMember(context.Context, *GetTrafficStateForMemberRequest) (*GetTrafficStateForMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrafficStateForMember not implemented")
}
func (UnimplementedSequencerServiceServer) GetTime(context.Context, *GetTimeRequest) (*GetTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTime not implemented")
}
func (UnimplementedSequencerServiceServer) mustEmbedUnimplementedSequencerServiceServer() {}
func (UnimplementedSequencerServiceServer) testEmbeddedByValue()                          {}

// UnsafeSequencerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SequencerServiceServer will
// result in compilation errors.
type UnsafeSequencerServiceServer interface {
	mustEmbedUnimplementedSequencerServiceServer()
}

func RegisterSequencerServiceServer(s grpc.ServiceRegistrar, srv SequencerServiceServer) {
	// If the following call pancis, it indicates UnimplementedSequencerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SequencerService_ServiceDesc, srv)
}

func _SequencerService_SendAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAsyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SequencerServiceServer).SendAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SequencerService_SendAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SequencerServiceServer).SendAsync(ctx, req.(*SendAsyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SequencerService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SequencerServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscriptionRequest, SubscriptionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SequencerService_SubscribeServer = grpc.ServerStreamingServer[SubscriptionResponse]

func _SequencerService_AcknowledgeSigned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeSignedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SequencerServiceServer).AcknowledgeSigned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SequencerService_AcknowledgeSigned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SequencerServiceServer).AcknowledgeSigned(ctx, req.(*AcknowledgeSignedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SequencerService_DownloadTopologyStateForInit_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadTopologyStateForInitRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SequencerServiceServer).DownloadTopologyStateForInit(m, &grpc.GenericServerStream[DownloadTopologyStateForInitRequest, DownloadTopologyStateForInitResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SequencerService_DownloadTopologyStateForInitServer = grpc.ServerStreamingServer[DownloadTopologyStateForInitResponse]

func _SequencerService_DownloadTopologyStateForInitHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadTopologyStateForInitHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SequencerServiceServer).DownloadTopologyStateForInitHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SequencerService_DownloadTopologyStateForInitHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SequencerServiceServer).DownloadTopologyStateForInitHash(ctx, req.(*DownloadTopologyStateForInitHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SequencerService_GetTrafficStateForMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrafficStateForMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SequencerServiceServer).GetTrafficStateForMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SequencerService_GetTrafficStateForMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SequencerServiceServer).GetTrafficStateForMember(ctx, req.(*GetTrafficStateForMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SequencerService_GetTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SequencerServiceServer).GetTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SequencerService_GetTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SequencerServiceServer).GetTime(ctx, req.(*GetTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SequencerService_ServiceDesc is the grpc.ServiceDesc for SequencerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SequencerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.digitalasset.canton.sequencer.api.v30.SequencerService",
	HandlerType: (*SequencerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAsync",
			Handler:    _SequencerService_SendAsync_Handler,
		},
		{
			MethodName: "AcknowledgeSigned",
			Handler:    _SequencerService_AcknowledgeSigned_Handler,
		},
		{
			MethodName: "DownloadTopologyStateForInitHash",
			Handler:    _SequencerService_DownloadTopologyStateForInitHash_Handler,
		},
		{
			MethodName: "GetTrafficStateForMember",
			Handler:    _SequencerService_GetTrafficStateForMember_Handler,
		},
		{
			MethodName: "GetTime",
			Handler:    _SequencerService_GetTime_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _SequencerService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadTopologyStateForInit",
			Handler:       _SequencerService_DownloadTopologyStateForInit_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "com/digitalasset/canton/sequencer/api/v30/sequencer_service.proto",
}
